// Package stub provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package stub

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// PlainTextOk Plain-text OK marker for probes
type PlainTextOk = string

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	AdminEmail openapi_types.Email `json:"admin_email"`
	AdminName  string              `json:"admin_name"`
	Password   string              `json:"password"`
	TenantName string              `json:"tenant_name"`
}

// RegisterResponse defines model for RegisterResponse.
type RegisterResponse struct {
	Email    openapi_types.Email `json:"email"`
	TenantId openapi_types.UUID  `json:"tenant_id"`
	UserId   openapi_types.UUID  `json:"user_id"`
}

// PostApiV1AuthRegisterJSONRequestBody defines body for PostApiV1AuthRegister for application/json ContentType.
type PostApiV1AuthRegisterJSONRequestBody = RegisterRequest
