# yaml-language-server: $schema=https://raw.githubusercontent.com/oapi-codegen/oapi-codegen/HEAD/configuration-schema.json
package: stub
generate:
  echo-server: true
  models: true
# Relative to backend/ when running: make generate
output: services/inventory/stub/openapi.gen.go
