package schemas

// CreateTenantAdminInput carries database payload for tenant+admin creation.
type CreateTenantAdminInput struct {
	TenantName    string
	TenantSlug    string
	AdminEmail    string
	AdminFullName string
	PasswordHash  string
	Role          string
}

// CreateTenantAdminResult returns identifiers generated by DB.
type CreateTenantAdminResult struct {
	TenantID string
	UserID   string
	Email    string
}

// AuthUserCredential is data required to authenticate a user.
type AuthUserCredential struct {
	ID           string
	TenantID     string
	Email        string
	PasswordHash string
	Role         string
}

// UserProfile is non-sensitive user fields for /auth/me.
type UserProfile struct {
	UserID   string `json:"user_id" gorm:"column:user_id"`
	TenantID string `json:"tenant_id" gorm:"column:tenant_id"`
	Email    string `json:"email"`
	FullName string `json:"full_name" gorm:"column:full_name"`
}
