package schemas

// CreateTenantAdminInput carries database payload for tenant+admin creation.
type CreateTenantAdminInput struct {
	TenantName   string
	AdminEmail   string
	PasswordHash string
	Role         string
}

// CreateTenantAdminResult returns identifiers generated by DB.
type CreateTenantAdminResult struct {
	TenantID string
	UserID   string
	Email    string
}
