// Package stub provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package stub

import (
	"fmt"
	"net/http"
	"time"

	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	JwtAuthScopes = "JwtAuth.Scopes"
)

// Defines values for CategoryListResponseSuccess.
const (
	CategoryListResponseSuccessTrue CategoryListResponseSuccess = true
)

// Defines values for CategorySuccessEnvelopeSuccess.
const (
	CategorySuccessEnvelopeSuccessTrue CategorySuccessEnvelopeSuccess = true
)

// Defines values for MovementStatus.
const (
	MovementStatusCancelled MovementStatus = "cancelled"
	MovementStatusConfirmed MovementStatus = "confirmed"
	MovementStatusDraft     MovementStatus = "draft"
)

// Defines values for MovementType.
const (
	MovementTypeAdjustment MovementType = "adjustment"
	MovementTypeInbound    MovementType = "inbound"
	MovementTypeOutbound   MovementType = "outbound"
	MovementTypeTransfer   MovementType = "transfer"
)

// Defines values for MovementListResponseSuccess.
const (
	MovementListResponseSuccessTrue MovementListResponseSuccess = true
)

// Defines values for MovementSuccessEnvelopeSuccess.
const (
	MovementSuccessEnvelopeSuccessTrue MovementSuccessEnvelopeSuccess = true
)

// Defines values for ProductListResponseSuccess.
const (
	ProductListResponseSuccessTrue ProductListResponseSuccess = true
)

// Defines values for ProductSuccessEnvelopeSuccess.
const (
	ProductSuccessEnvelopeSuccessTrue ProductSuccessEnvelopeSuccess = true
)

// Defines values for WarehouseListResponseSuccess.
const (
	WarehouseListResponseSuccessTrue WarehouseListResponseSuccess = true
)

// Defines values for WarehouseSuccessEnvelopeSuccess.
const (
	WarehouseSuccessEnvelopeSuccessTrue WarehouseSuccessEnvelopeSuccess = true
)

// Defines values for Order.
const (
	OrderAsc  Order = "asc"
	OrderDesc Order = "desc"
)

// Defines values for GetApiV1InventoryCategoriesParamsOrder.
const (
	GetApiV1InventoryCategoriesParamsOrderAsc  GetApiV1InventoryCategoriesParamsOrder = "asc"
	GetApiV1InventoryCategoriesParamsOrderDesc GetApiV1InventoryCategoriesParamsOrder = "desc"
)

// Defines values for GetApiV1InventoryMovementsParamsType.
const (
	GetApiV1InventoryMovementsParamsTypeAdjustment GetApiV1InventoryMovementsParamsType = "adjustment"
	GetApiV1InventoryMovementsParamsTypeInbound    GetApiV1InventoryMovementsParamsType = "inbound"
	GetApiV1InventoryMovementsParamsTypeOutbound   GetApiV1InventoryMovementsParamsType = "outbound"
	GetApiV1InventoryMovementsParamsTypeTransfer   GetApiV1InventoryMovementsParamsType = "transfer"
)

// Defines values for GetApiV1InventoryMovementsParamsStatus.
const (
	GetApiV1InventoryMovementsParamsStatusCancelled GetApiV1InventoryMovementsParamsStatus = "cancelled"
	GetApiV1InventoryMovementsParamsStatusConfirmed GetApiV1InventoryMovementsParamsStatus = "confirmed"
	GetApiV1InventoryMovementsParamsStatusDraft     GetApiV1InventoryMovementsParamsStatus = "draft"
)

// Defines values for GetApiV1InventoryMovementsParamsOrder.
const (
	GetApiV1InventoryMovementsParamsOrderAsc  GetApiV1InventoryMovementsParamsOrder = "asc"
	GetApiV1InventoryMovementsParamsOrderDesc GetApiV1InventoryMovementsParamsOrder = "desc"
)

// Defines values for GetApiV1InventoryProductsParamsOrder.
const (
	GetApiV1InventoryProductsParamsOrderAsc  GetApiV1InventoryProductsParamsOrder = "asc"
	GetApiV1InventoryProductsParamsOrderDesc GetApiV1InventoryProductsParamsOrder = "desc"
)

// Defines values for GetApiV1InventoryWarehousesParamsOrder.
const (
	Asc  GetApiV1InventoryWarehousesParamsOrder = "asc"
	Desc GetApiV1InventoryWarehousesParamsOrder = "desc"
)

// AdjustmentMovementCreateRequest defines model for AdjustmentMovementCreateRequest.
type AdjustmentMovementCreateRequest struct {
	DestinationWarehouseId *openapi_types.UUID  `json:"destination_warehouse_id"`
	IdempotencyKey         *string              `json:"idempotency_key,omitempty"`
	Lines                  []MovementLineCreate `json:"lines"`
	Notes                  *string              `json:"notes,omitempty"`
	ReferenceNumber        string               `json:"reference_number"`
	SourceWarehouseId      *openapi_types.UUID  `json:"source_warehouse_id"`
}

// Category defines model for Category.
type Category struct {
	CreatedAt   time.Time           `json:"created_at"`
	DeletedAt   *time.Time          `json:"deleted_at"`
	Description *string             `json:"description,omitempty"`
	Id          openapi_types.UUID  `json:"id"`
	Name        string              `json:"name"`
	ParentId    *openapi_types.UUID `json:"parent_id"`
	SortOrder   *int32              `json:"sort_order,omitempty"`
	TenantId    openapi_types.UUID  `json:"tenant_id"`
	UpdatedAt   time.Time           `json:"updated_at"`
}

// CategoryCreateRequest defines model for CategoryCreateRequest.
type CategoryCreateRequest struct {
	Description *string             `json:"description,omitempty"`
	Name        string              `json:"name"`
	ParentId    *openapi_types.UUID `json:"parent_id"`
	SortOrder   *int32              `json:"sort_order,omitempty"`
}

// CategoryListResponse defines model for CategoryListResponse.
type CategoryListResponse struct {
	Data []Category `json:"data"`

	// Meta §9 meta for JSON success responses (list endpoints include pagination).
	Meta    SuccessMeta                 `json:"meta"`
	Success CategoryListResponseSuccess `json:"success"`
}

// CategoryListResponseSuccess defines model for CategoryListResponse.Success.
type CategoryListResponseSuccess bool

// CategorySuccessEnvelope defines model for CategorySuccessEnvelope.
type CategorySuccessEnvelope struct {
	Data Category `json:"data"`

	// Meta §9 meta for JSON success responses (list endpoints include pagination).
	Meta    *SuccessMeta                   `json:"meta,omitempty"`
	Success CategorySuccessEnvelopeSuccess `json:"success"`
}

// CategorySuccessEnvelopeSuccess defines model for CategorySuccessEnvelope.Success.
type CategorySuccessEnvelopeSuccess bool

// CategoryUpdateRequest defines model for CategoryUpdateRequest.
type CategoryUpdateRequest struct {
	Description *string             `json:"description,omitempty"`
	Name        *string             `json:"name,omitempty"`
	ParentId    *openapi_types.UUID `json:"parent_id"`
	SortOrder   *int32              `json:"sort_order,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Error Machine-readable error message
	Error string `json:"error"`
}

// InboundMovementCreateRequest defines model for InboundMovementCreateRequest.
type InboundMovementCreateRequest struct {
	DestinationWarehouseId openapi_types.UUID   `json:"destination_warehouse_id"`
	IdempotencyKey         *string              `json:"idempotency_key,omitempty"`
	Lines                  []MovementLineCreate `json:"lines"`
	Notes                  *string              `json:"notes,omitempty"`
	ReferenceNumber        string               `json:"reference_number"`
}

// Movement defines model for Movement.
type Movement struct {
	CreatedAt              time.Time           `json:"created_at"`
	CreatedBy              openapi_types.UUID  `json:"created_by"`
	DestinationWarehouseId *openapi_types.UUID `json:"destination_warehouse_id"`
	Id                     openapi_types.UUID  `json:"id"`
	IdempotencyKey         *string             `json:"idempotency_key"`
	Lines                  *[]MovementLine     `json:"lines,omitempty"`
	Notes                  *string             `json:"notes"`
	ReferenceNumber        string              `json:"reference_number"`
	SourceWarehouseId      *openapi_types.UUID `json:"source_warehouse_id"`
	Status                 MovementStatus      `json:"status"`
	TenantId               openapi_types.UUID  `json:"tenant_id"`
	Type                   MovementType        `json:"type"`
	UpdatedAt              time.Time           `json:"updated_at"`
}

// MovementStatus defines model for Movement.Status.
type MovementStatus string

// MovementType defines model for Movement.Type.
type MovementType string

// MovementDraftFields defines model for MovementDraftFields.
type MovementDraftFields struct {
	IdempotencyKey  *string              `json:"idempotency_key,omitempty"`
	Lines           []MovementLineCreate `json:"lines"`
	Notes           *string              `json:"notes,omitempty"`
	ReferenceNumber string               `json:"reference_number"`
}

// MovementLine defines model for MovementLine.
type MovementLine struct {
	CreatedAt  time.Time          `json:"created_at"`
	Id         openapi_types.UUID `json:"id"`
	MovementId openapi_types.UUID `json:"movement_id"`
	Notes      *string            `json:"notes"`
	ProductId  openapi_types.UUID `json:"product_id"`
	Quantity   int32              `json:"quantity"`
}

// MovementLineCreate defines model for MovementLineCreate.
type MovementLineCreate struct {
	Notes     *string            `json:"notes,omitempty"`
	ProductId openapi_types.UUID `json:"product_id"`
	Quantity  int32              `json:"quantity"`
}

// MovementListResponse defines model for MovementListResponse.
type MovementListResponse struct {
	Data []Movement `json:"data"`

	// Meta §9 meta for JSON success responses (list endpoints include pagination).
	Meta    SuccessMeta                 `json:"meta"`
	Success MovementListResponseSuccess `json:"success"`
}

// MovementListResponseSuccess defines model for MovementListResponse.Success.
type MovementListResponseSuccess bool

// MovementSuccessEnvelope defines model for MovementSuccessEnvelope.
type MovementSuccessEnvelope struct {
	Data Movement `json:"data"`

	// Meta §9 meta for JSON success responses (list endpoints include pagination).
	Meta    *SuccessMeta                   `json:"meta,omitempty"`
	Success MovementSuccessEnvelopeSuccess `json:"success"`
}

// MovementSuccessEnvelopeSuccess defines model for MovementSuccessEnvelope.Success.
type MovementSuccessEnvelopeSuccess bool

// OutboundMovementCreateRequest defines model for OutboundMovementCreateRequest.
type OutboundMovementCreateRequest struct {
	IdempotencyKey    *string              `json:"idempotency_key,omitempty"`
	Lines             []MovementLineCreate `json:"lines"`
	Notes             *string              `json:"notes,omitempty"`
	ReferenceNumber   string               `json:"reference_number"`
	SourceWarehouseId openapi_types.UUID   `json:"source_warehouse_id"`
}

// PaginationMeta defines model for PaginationMeta.
type PaginationMeta struct {
	Page       int32 `json:"page"`
	PerPage    int32 `json:"per_page"`
	Total      int64 `json:"total"`
	TotalPages int32 `json:"total_pages"`
}

// PlainTextOk Plain-text OK marker for probes
type PlainTextOk = string

// Product defines model for Product.
type Product struct {
	CategoryId   *openapi_types.UUID     `json:"category_id"`
	CreatedAt    time.Time               `json:"created_at"`
	DeletedAt    *time.Time              `json:"deleted_at"`
	Description  *string                 `json:"description,omitempty"`
	Id           openapi_types.UUID      `json:"id"`
	Metadata     *map[string]interface{} `json:"metadata,omitempty"`
	Name         string                  `json:"name"`
	Price        *float64                `json:"price,omitempty"`
	ReorderLevel *int32                  `json:"reorder_level,omitempty"`
	Sku          string                  `json:"sku"`
	TenantId     openapi_types.UUID      `json:"tenant_id"`
	Unit         *string                 `json:"unit,omitempty"`
	UpdatedAt    time.Time               `json:"updated_at"`
}

// ProductCreateRequest defines model for ProductCreateRequest.
type ProductCreateRequest struct {
	CategoryId   *openapi_types.UUID     `json:"category_id"`
	Description  *string                 `json:"description,omitempty"`
	Metadata     *map[string]interface{} `json:"metadata,omitempty"`
	Name         string                  `json:"name"`
	Price        *float64                `json:"price,omitempty"`
	ReorderLevel *int32                  `json:"reorder_level,omitempty"`
	Sku          string                  `json:"sku"`
	Unit         *string                 `json:"unit,omitempty"`
}

// ProductListResponse defines model for ProductListResponse.
type ProductListResponse struct {
	Data []Product `json:"data"`

	// Meta §9 meta for JSON success responses (list endpoints include pagination).
	Meta    SuccessMeta                `json:"meta"`
	Success ProductListResponseSuccess `json:"success"`
}

// ProductListResponseSuccess defines model for ProductListResponse.Success.
type ProductListResponseSuccess bool

// ProductSuccessEnvelope defines model for ProductSuccessEnvelope.
type ProductSuccessEnvelope struct {
	Data Product `json:"data"`

	// Meta §9 meta for JSON success responses (list endpoints include pagination).
	Meta    *SuccessMeta                  `json:"meta,omitempty"`
	Success ProductSuccessEnvelopeSuccess `json:"success"`
}

// ProductSuccessEnvelopeSuccess defines model for ProductSuccessEnvelope.Success.
type ProductSuccessEnvelopeSuccess bool

// ProductUpdateRequest defines model for ProductUpdateRequest.
type ProductUpdateRequest struct {
	CategoryId   *openapi_types.UUID     `json:"category_id"`
	Description  *string                 `json:"description,omitempty"`
	Metadata     *map[string]interface{} `json:"metadata,omitempty"`
	Name         *string                 `json:"name,omitempty"`
	Price        *float64                `json:"price,omitempty"`
	ReorderLevel *int32                  `json:"reorder_level,omitempty"`
	Sku          *string                 `json:"sku,omitempty"`
	Unit         *string                 `json:"unit,omitempty"`
}

// SuccessMeta §9 meta for JSON success responses (list endpoints include pagination).
type SuccessMeta struct {
	Pagination *PaginationMeta `json:"pagination,omitempty"`
	RequestId  *string         `json:"request_id,omitempty"`
}

// TransferMovementCreateRequest defines model for TransferMovementCreateRequest.
type TransferMovementCreateRequest struct {
	DestinationWarehouseId openapi_types.UUID   `json:"destination_warehouse_id"`
	IdempotencyKey         *string              `json:"idempotency_key,omitempty"`
	Lines                  []MovementLineCreate `json:"lines"`
	Notes                  *string              `json:"notes,omitempty"`
	ReferenceNumber        string               `json:"reference_number"`
	SourceWarehouseId      openapi_types.UUID   `json:"source_warehouse_id"`
}

// Warehouse defines model for Warehouse.
type Warehouse struct {
	Address   *string            `json:"address,omitempty"`
	Code      *string            `json:"code,omitempty"`
	CreatedAt time.Time          `json:"created_at"`
	DeletedAt *time.Time         `json:"deleted_at"`
	Id        openapi_types.UUID `json:"id"`
	IsActive  *bool              `json:"is_active,omitempty"`
	Name      string             `json:"name"`
	TenantId  openapi_types.UUID `json:"tenant_id"`
	UpdatedAt time.Time          `json:"updated_at"`
}

// WarehouseCreateRequest defines model for WarehouseCreateRequest.
type WarehouseCreateRequest struct {
	Address  *string `json:"address,omitempty"`
	Code     string  `json:"code"`
	IsActive *bool   `json:"is_active,omitempty"`
	Name     string  `json:"name"`
}

// WarehouseListResponse defines model for WarehouseListResponse.
type WarehouseListResponse struct {
	Data []Warehouse `json:"data"`

	// Meta §9 meta for JSON success responses (list endpoints include pagination).
	Meta    SuccessMeta                  `json:"meta"`
	Success WarehouseListResponseSuccess `json:"success"`
}

// WarehouseListResponseSuccess defines model for WarehouseListResponse.Success.
type WarehouseListResponseSuccess bool

// WarehouseSuccessEnvelope defines model for WarehouseSuccessEnvelope.
type WarehouseSuccessEnvelope struct {
	Data Warehouse `json:"data"`

	// Meta §9 meta for JSON success responses (list endpoints include pagination).
	Meta    *SuccessMeta                    `json:"meta,omitempty"`
	Success WarehouseSuccessEnvelopeSuccess `json:"success"`
}

// WarehouseSuccessEnvelopeSuccess defines model for WarehouseSuccessEnvelope.Success.
type WarehouseSuccessEnvelopeSuccess bool

// WarehouseUpdateRequest defines model for WarehouseUpdateRequest.
type WarehouseUpdateRequest struct {
	Address  *string `json:"address,omitempty"`
	Code     *string `json:"code,omitempty"`
	IsActive *bool   `json:"is_active,omitempty"`
	Name     *string `json:"name,omitempty"`
}

// CategoryId defines model for CategoryId.
type CategoryId = openapi_types.UUID

// MovementId defines model for MovementId.
type MovementId = openapi_types.UUID

// Order defines model for Order.
type Order string

// Page defines model for Page.
type Page = int

// PerPage defines model for PerPage.
type PerPage = int

// ProductId defines model for ProductId.
type ProductId = openapi_types.UUID

// Search defines model for Search.
type Search = string

// Sort Field name to sort by (domain-specific)
type Sort = string

// WarehouseId defines model for WarehouseId.
type WarehouseId = openapi_types.UUID

// BadRequestError defines model for BadRequestError.
type BadRequestError = ErrorResponse

// ConflictError defines model for ConflictError.
type ConflictError = ErrorResponse

// NotFoundError defines model for NotFoundError.
type NotFoundError = ErrorResponse

// UnauthorizedError defines model for UnauthorizedError.
type UnauthorizedError = ErrorResponse

// UnprocessableEntityError defines model for UnprocessableEntityError.
type UnprocessableEntityError = ErrorResponse

// GetApiV1InventoryCategoriesParams defines parameters for GetApiV1InventoryCategories.
type GetApiV1InventoryCategoriesParams struct {
	Page    *Page                                   `form:"page,omitempty" json:"page,omitempty"`
	PerPage *PerPage                                `form:"per_page,omitempty" json:"per_page,omitempty"`
	Search  *Search                                 `form:"search,omitempty" json:"search,omitempty"`
	Sort    *Sort                                   `form:"sort,omitempty" json:"sort,omitempty"`
	Order   *GetApiV1InventoryCategoriesParamsOrder `form:"order,omitempty" json:"order,omitempty"`
}

// GetApiV1InventoryCategoriesParamsOrder defines parameters for GetApiV1InventoryCategories.
type GetApiV1InventoryCategoriesParamsOrder string

// GetApiV1InventoryMovementsParams defines parameters for GetApiV1InventoryMovements.
type GetApiV1InventoryMovementsParams struct {
	Page    *Page                                   `form:"page,omitempty" json:"page,omitempty"`
	PerPage *PerPage                                `form:"per_page,omitempty" json:"per_page,omitempty"`
	Search  *Search                                 `form:"search,omitempty" json:"search,omitempty"`
	Type    *GetApiV1InventoryMovementsParamsType   `form:"type,omitempty" json:"type,omitempty"`
	Status  *GetApiV1InventoryMovementsParamsStatus `form:"status,omitempty" json:"status,omitempty"`
	Sort    *Sort                                   `form:"sort,omitempty" json:"sort,omitempty"`
	Order   *GetApiV1InventoryMovementsParamsOrder  `form:"order,omitempty" json:"order,omitempty"`
}

// GetApiV1InventoryMovementsParamsType defines parameters for GetApiV1InventoryMovements.
type GetApiV1InventoryMovementsParamsType string

// GetApiV1InventoryMovementsParamsStatus defines parameters for GetApiV1InventoryMovements.
type GetApiV1InventoryMovementsParamsStatus string

// GetApiV1InventoryMovementsParamsOrder defines parameters for GetApiV1InventoryMovements.
type GetApiV1InventoryMovementsParamsOrder string

// GetApiV1InventoryProductsParams defines parameters for GetApiV1InventoryProducts.
type GetApiV1InventoryProductsParams struct {
	Page    *Page                                 `form:"page,omitempty" json:"page,omitempty"`
	PerPage *PerPage                              `form:"per_page,omitempty" json:"per_page,omitempty"`
	Search  *Search                               `form:"search,omitempty" json:"search,omitempty"`
	Sort    *Sort                                 `form:"sort,omitempty" json:"sort,omitempty"`
	Order   *GetApiV1InventoryProductsParamsOrder `form:"order,omitempty" json:"order,omitempty"`

	// CategoryId Filter by category UUID
	CategoryId *openapi_types.UUID `form:"category_id,omitempty" json:"category_id,omitempty"`
}

// GetApiV1InventoryProductsParamsOrder defines parameters for GetApiV1InventoryProducts.
type GetApiV1InventoryProductsParamsOrder string

// GetApiV1InventoryWarehousesParams defines parameters for GetApiV1InventoryWarehouses.
type GetApiV1InventoryWarehousesParams struct {
	Page    *Page                                   `form:"page,omitempty" json:"page,omitempty"`
	PerPage *PerPage                                `form:"per_page,omitempty" json:"per_page,omitempty"`
	Search  *Search                                 `form:"search,omitempty" json:"search,omitempty"`
	Sort    *Sort                                   `form:"sort,omitempty" json:"sort,omitempty"`
	Order   *GetApiV1InventoryWarehousesParamsOrder `form:"order,omitempty" json:"order,omitempty"`
}

// GetApiV1InventoryWarehousesParamsOrder defines parameters for GetApiV1InventoryWarehouses.
type GetApiV1InventoryWarehousesParamsOrder string

// PostApiV1InventoryCategoriesJSONRequestBody defines body for PostApiV1InventoryCategories for application/json ContentType.
type PostApiV1InventoryCategoriesJSONRequestBody = CategoryCreateRequest

// PutApiV1InventoryCategoriesCategoryIdJSONRequestBody defines body for PutApiV1InventoryCategoriesCategoryId for application/json ContentType.
type PutApiV1InventoryCategoriesCategoryIdJSONRequestBody = CategoryUpdateRequest

// PostApiV1InventoryMovementsAdjustmentJSONRequestBody defines body for PostApiV1InventoryMovementsAdjustment for application/json ContentType.
type PostApiV1InventoryMovementsAdjustmentJSONRequestBody = AdjustmentMovementCreateRequest

// PostApiV1InventoryMovementsInboundJSONRequestBody defines body for PostApiV1InventoryMovementsInbound for application/json ContentType.
type PostApiV1InventoryMovementsInboundJSONRequestBody = InboundMovementCreateRequest

// PostApiV1InventoryMovementsOutboundJSONRequestBody defines body for PostApiV1InventoryMovementsOutbound for application/json ContentType.
type PostApiV1InventoryMovementsOutboundJSONRequestBody = OutboundMovementCreateRequest

// PostApiV1InventoryMovementsTransferJSONRequestBody defines body for PostApiV1InventoryMovementsTransfer for application/json ContentType.
type PostApiV1InventoryMovementsTransferJSONRequestBody = TransferMovementCreateRequest

// PostApiV1InventoryProductsJSONRequestBody defines body for PostApiV1InventoryProducts for application/json ContentType.
type PostApiV1InventoryProductsJSONRequestBody = ProductCreateRequest

// PutApiV1InventoryProductsProductIdJSONRequestBody defines body for PutApiV1InventoryProductsProductId for application/json ContentType.
type PutApiV1InventoryProductsProductIdJSONRequestBody = ProductUpdateRequest

// PostApiV1InventoryWarehousesJSONRequestBody defines body for PostApiV1InventoryWarehouses for application/json ContentType.
type PostApiV1InventoryWarehousesJSONRequestBody = WarehouseCreateRequest

// PutApiV1InventoryWarehousesWarehouseIdJSONRequestBody defines body for PutApiV1InventoryWarehousesWarehouseId for application/json ContentType.
type PutApiV1InventoryWarehousesWarehouseIdJSONRequestBody = WarehouseUpdateRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List categories
	// (GET /api/v1/inventory/categories)
	GetApiV1InventoryCategories(ctx echo.Context, params GetApiV1InventoryCategoriesParams) error
	// Create category
	// (POST /api/v1/inventory/categories)
	PostApiV1InventoryCategories(ctx echo.Context) error
	// Delete category (soft delete when applicable)
	// (DELETE /api/v1/inventory/categories/{categoryId})
	DeleteApiV1InventoryCategoriesCategoryId(ctx echo.Context, categoryId CategoryId) error
	// Get category by ID
	// (GET /api/v1/inventory/categories/{categoryId})
	GetApiV1InventoryCategoriesCategoryId(ctx echo.Context, categoryId CategoryId) error
	// Update category
	// (PUT /api/v1/inventory/categories/{categoryId})
	PutApiV1InventoryCategoriesCategoryId(ctx echo.Context, categoryId CategoryId) error
	// Inventory service liveness under API prefix
	// (GET /api/v1/inventory/health)
	GetInventoryHealth(ctx echo.Context) error
	// List movements
	// (GET /api/v1/inventory/movements)
	GetApiV1InventoryMovements(ctx echo.Context, params GetApiV1InventoryMovementsParams) error
	// Create draft adjustment movement
	// (POST /api/v1/inventory/movements/adjustment)
	PostApiV1InventoryMovementsAdjustment(ctx echo.Context) error
	// Create draft inbound movement
	// (POST /api/v1/inventory/movements/inbound)
	PostApiV1InventoryMovementsInbound(ctx echo.Context) error
	// Create draft outbound movement
	// (POST /api/v1/inventory/movements/outbound)
	PostApiV1InventoryMovementsOutbound(ctx echo.Context) error
	// Create draft transfer movement
	// (POST /api/v1/inventory/movements/transfer)
	PostApiV1InventoryMovementsTransfer(ctx echo.Context) error
	// Get movement with lines
	// (GET /api/v1/inventory/movements/{movementId})
	GetApiV1InventoryMovementsMovementId(ctx echo.Context, movementId MovementId) error
	// Cancel draft movement
	// (POST /api/v1/inventory/movements/{movementId}/cancel)
	PostApiV1InventoryMovementsMovementIdCancel(ctx echo.Context, movementId MovementId) error
	// Confirm draft movement (apply stock, audit, outbox)
	// (POST /api/v1/inventory/movements/{movementId}/confirm)
	PostApiV1InventoryMovementsMovementIdConfirm(ctx echo.Context, movementId MovementId) error
	// List products
	// (GET /api/v1/inventory/products)
	GetApiV1InventoryProducts(ctx echo.Context, params GetApiV1InventoryProductsParams) error
	// Create product
	// (POST /api/v1/inventory/products)
	PostApiV1InventoryProducts(ctx echo.Context) error
	// Delete product (soft delete)
	// (DELETE /api/v1/inventory/products/{productId})
	DeleteApiV1InventoryProductsProductId(ctx echo.Context, productId ProductId) error
	// Get product by ID
	// (GET /api/v1/inventory/products/{productId})
	GetApiV1InventoryProductsProductId(ctx echo.Context, productId ProductId) error
	// Update product
	// (PUT /api/v1/inventory/products/{productId})
	PutApiV1InventoryProductsProductId(ctx echo.Context, productId ProductId) error
	// Restore soft-deleted product
	// (POST /api/v1/inventory/products/{productId}/restore)
	PostApiV1InventoryProductsProductIdRestore(ctx echo.Context, productId ProductId) error
	// List warehouses
	// (GET /api/v1/inventory/warehouses)
	GetApiV1InventoryWarehouses(ctx echo.Context, params GetApiV1InventoryWarehousesParams) error
	// Create warehouse
	// (POST /api/v1/inventory/warehouses)
	PostApiV1InventoryWarehouses(ctx echo.Context) error
	// Delete warehouse
	// (DELETE /api/v1/inventory/warehouses/{warehouseId})
	DeleteApiV1InventoryWarehousesWarehouseId(ctx echo.Context, warehouseId WarehouseId) error
	// Get warehouse by ID
	// (GET /api/v1/inventory/warehouses/{warehouseId})
	GetApiV1InventoryWarehousesWarehouseId(ctx echo.Context, warehouseId WarehouseId) error
	// Update warehouse
	// (PUT /api/v1/inventory/warehouses/{warehouseId})
	PutApiV1InventoryWarehousesWarehouseId(ctx echo.Context, warehouseId WarehouseId) error
	// Liveness probe
	// (GET /health)
	GetHealth(ctx echo.Context) error
	// Readiness probe (database)
	// (GET /ready)
	GetReady(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetApiV1InventoryCategories converts echo context to params.
func (w *ServerInterfaceWrapper) GetApiV1InventoryCategories(ctx echo.Context) error {
	var err error

	ctx.Set(JwtAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetApiV1InventoryCategoriesParams
	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", ctx.QueryParams(), &params.Page)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter page: %s", err))
	}

	// ------------- Optional query parameter "per_page" -------------

	err = runtime.BindQueryParameter("form", true, false, "per_page", ctx.QueryParams(), &params.PerPage)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter per_page: %s", err))
	}

	// ------------- Optional query parameter "search" -------------

	err = runtime.BindQueryParameter("form", true, false, "search", ctx.QueryParams(), &params.Search)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter search: %s", err))
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort", ctx.QueryParams(), &params.Sort)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter sort: %s", err))
	}

	// ------------- Optional query parameter "order" -------------

	err = runtime.BindQueryParameter("form", true, false, "order", ctx.QueryParams(), &params.Order)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter order: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetApiV1InventoryCategories(ctx, params)
	return err
}

// PostApiV1InventoryCategories converts echo context to params.
func (w *ServerInterfaceWrapper) PostApiV1InventoryCategories(ctx echo.Context) error {
	var err error

	ctx.Set(JwtAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostApiV1InventoryCategories(ctx)
	return err
}

// DeleteApiV1InventoryCategoriesCategoryId converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteApiV1InventoryCategoriesCategoryId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "categoryId" -------------
	var categoryId CategoryId

	err = runtime.BindStyledParameterWithOptions("simple", "categoryId", ctx.Param("categoryId"), &categoryId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter categoryId: %s", err))
	}

	ctx.Set(JwtAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteApiV1InventoryCategoriesCategoryId(ctx, categoryId)
	return err
}

// GetApiV1InventoryCategoriesCategoryId converts echo context to params.
func (w *ServerInterfaceWrapper) GetApiV1InventoryCategoriesCategoryId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "categoryId" -------------
	var categoryId CategoryId

	err = runtime.BindStyledParameterWithOptions("simple", "categoryId", ctx.Param("categoryId"), &categoryId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter categoryId: %s", err))
	}

	ctx.Set(JwtAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetApiV1InventoryCategoriesCategoryId(ctx, categoryId)
	return err
}

// PutApiV1InventoryCategoriesCategoryId converts echo context to params.
func (w *ServerInterfaceWrapper) PutApiV1InventoryCategoriesCategoryId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "categoryId" -------------
	var categoryId CategoryId

	err = runtime.BindStyledParameterWithOptions("simple", "categoryId", ctx.Param("categoryId"), &categoryId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter categoryId: %s", err))
	}

	ctx.Set(JwtAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PutApiV1InventoryCategoriesCategoryId(ctx, categoryId)
	return err
}

// GetInventoryHealth converts echo context to params.
func (w *ServerInterfaceWrapper) GetInventoryHealth(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetInventoryHealth(ctx)
	return err
}

// GetApiV1InventoryMovements converts echo context to params.
func (w *ServerInterfaceWrapper) GetApiV1InventoryMovements(ctx echo.Context) error {
	var err error

	ctx.Set(JwtAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetApiV1InventoryMovementsParams
	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", ctx.QueryParams(), &params.Page)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter page: %s", err))
	}

	// ------------- Optional query parameter "per_page" -------------

	err = runtime.BindQueryParameter("form", true, false, "per_page", ctx.QueryParams(), &params.PerPage)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter per_page: %s", err))
	}

	// ------------- Optional query parameter "search" -------------

	err = runtime.BindQueryParameter("form", true, false, "search", ctx.QueryParams(), &params.Search)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter search: %s", err))
	}

	// ------------- Optional query parameter "type" -------------

	err = runtime.BindQueryParameter("form", true, false, "type", ctx.QueryParams(), &params.Type)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter type: %s", err))
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, false, "status", ctx.QueryParams(), &params.Status)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter status: %s", err))
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort", ctx.QueryParams(), &params.Sort)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter sort: %s", err))
	}

	// ------------- Optional query parameter "order" -------------

	err = runtime.BindQueryParameter("form", true, false, "order", ctx.QueryParams(), &params.Order)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter order: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetApiV1InventoryMovements(ctx, params)
	return err
}

// PostApiV1InventoryMovementsAdjustment converts echo context to params.
func (w *ServerInterfaceWrapper) PostApiV1InventoryMovementsAdjustment(ctx echo.Context) error {
	var err error

	ctx.Set(JwtAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostApiV1InventoryMovementsAdjustment(ctx)
	return err
}

// PostApiV1InventoryMovementsInbound converts echo context to params.
func (w *ServerInterfaceWrapper) PostApiV1InventoryMovementsInbound(ctx echo.Context) error {
	var err error

	ctx.Set(JwtAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostApiV1InventoryMovementsInbound(ctx)
	return err
}

// PostApiV1InventoryMovementsOutbound converts echo context to params.
func (w *ServerInterfaceWrapper) PostApiV1InventoryMovementsOutbound(ctx echo.Context) error {
	var err error

	ctx.Set(JwtAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostApiV1InventoryMovementsOutbound(ctx)
	return err
}

// PostApiV1InventoryMovementsTransfer converts echo context to params.
func (w *ServerInterfaceWrapper) PostApiV1InventoryMovementsTransfer(ctx echo.Context) error {
	var err error

	ctx.Set(JwtAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostApiV1InventoryMovementsTransfer(ctx)
	return err
}

// GetApiV1InventoryMovementsMovementId converts echo context to params.
func (w *ServerInterfaceWrapper) GetApiV1InventoryMovementsMovementId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "movementId" -------------
	var movementId MovementId

	err = runtime.BindStyledParameterWithOptions("simple", "movementId", ctx.Param("movementId"), &movementId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter movementId: %s", err))
	}

	ctx.Set(JwtAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetApiV1InventoryMovementsMovementId(ctx, movementId)
	return err
}

// PostApiV1InventoryMovementsMovementIdCancel converts echo context to params.
func (w *ServerInterfaceWrapper) PostApiV1InventoryMovementsMovementIdCancel(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "movementId" -------------
	var movementId MovementId

	err = runtime.BindStyledParameterWithOptions("simple", "movementId", ctx.Param("movementId"), &movementId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter movementId: %s", err))
	}

	ctx.Set(JwtAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostApiV1InventoryMovementsMovementIdCancel(ctx, movementId)
	return err
}

// PostApiV1InventoryMovementsMovementIdConfirm converts echo context to params.
func (w *ServerInterfaceWrapper) PostApiV1InventoryMovementsMovementIdConfirm(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "movementId" -------------
	var movementId MovementId

	err = runtime.BindStyledParameterWithOptions("simple", "movementId", ctx.Param("movementId"), &movementId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter movementId: %s", err))
	}

	ctx.Set(JwtAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostApiV1InventoryMovementsMovementIdConfirm(ctx, movementId)
	return err
}

// GetApiV1InventoryProducts converts echo context to params.
func (w *ServerInterfaceWrapper) GetApiV1InventoryProducts(ctx echo.Context) error {
	var err error

	ctx.Set(JwtAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetApiV1InventoryProductsParams
	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", ctx.QueryParams(), &params.Page)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter page: %s", err))
	}

	// ------------- Optional query parameter "per_page" -------------

	err = runtime.BindQueryParameter("form", true, false, "per_page", ctx.QueryParams(), &params.PerPage)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter per_page: %s", err))
	}

	// ------------- Optional query parameter "search" -------------

	err = runtime.BindQueryParameter("form", true, false, "search", ctx.QueryParams(), &params.Search)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter search: %s", err))
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort", ctx.QueryParams(), &params.Sort)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter sort: %s", err))
	}

	// ------------- Optional query parameter "order" -------------

	err = runtime.BindQueryParameter("form", true, false, "order", ctx.QueryParams(), &params.Order)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter order: %s", err))
	}

	// ------------- Optional query parameter "category_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "category_id", ctx.QueryParams(), &params.CategoryId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter category_id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetApiV1InventoryProducts(ctx, params)
	return err
}

// PostApiV1InventoryProducts converts echo context to params.
func (w *ServerInterfaceWrapper) PostApiV1InventoryProducts(ctx echo.Context) error {
	var err error

	ctx.Set(JwtAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostApiV1InventoryProducts(ctx)
	return err
}

// DeleteApiV1InventoryProductsProductId converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteApiV1InventoryProductsProductId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "productId" -------------
	var productId ProductId

	err = runtime.BindStyledParameterWithOptions("simple", "productId", ctx.Param("productId"), &productId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter productId: %s", err))
	}

	ctx.Set(JwtAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteApiV1InventoryProductsProductId(ctx, productId)
	return err
}

// GetApiV1InventoryProductsProductId converts echo context to params.
func (w *ServerInterfaceWrapper) GetApiV1InventoryProductsProductId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "productId" -------------
	var productId ProductId

	err = runtime.BindStyledParameterWithOptions("simple", "productId", ctx.Param("productId"), &productId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter productId: %s", err))
	}

	ctx.Set(JwtAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetApiV1InventoryProductsProductId(ctx, productId)
	return err
}

// PutApiV1InventoryProductsProductId converts echo context to params.
func (w *ServerInterfaceWrapper) PutApiV1InventoryProductsProductId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "productId" -------------
	var productId ProductId

	err = runtime.BindStyledParameterWithOptions("simple", "productId", ctx.Param("productId"), &productId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter productId: %s", err))
	}

	ctx.Set(JwtAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PutApiV1InventoryProductsProductId(ctx, productId)
	return err
}

// PostApiV1InventoryProductsProductIdRestore converts echo context to params.
func (w *ServerInterfaceWrapper) PostApiV1InventoryProductsProductIdRestore(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "productId" -------------
	var productId ProductId

	err = runtime.BindStyledParameterWithOptions("simple", "productId", ctx.Param("productId"), &productId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter productId: %s", err))
	}

	ctx.Set(JwtAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostApiV1InventoryProductsProductIdRestore(ctx, productId)
	return err
}

// GetApiV1InventoryWarehouses converts echo context to params.
func (w *ServerInterfaceWrapper) GetApiV1InventoryWarehouses(ctx echo.Context) error {
	var err error

	ctx.Set(JwtAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetApiV1InventoryWarehousesParams
	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", ctx.QueryParams(), &params.Page)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter page: %s", err))
	}

	// ------------- Optional query parameter "per_page" -------------

	err = runtime.BindQueryParameter("form", true, false, "per_page", ctx.QueryParams(), &params.PerPage)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter per_page: %s", err))
	}

	// ------------- Optional query parameter "search" -------------

	err = runtime.BindQueryParameter("form", true, false, "search", ctx.QueryParams(), &params.Search)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter search: %s", err))
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort", ctx.QueryParams(), &params.Sort)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter sort: %s", err))
	}

	// ------------- Optional query parameter "order" -------------

	err = runtime.BindQueryParameter("form", true, false, "order", ctx.QueryParams(), &params.Order)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter order: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetApiV1InventoryWarehouses(ctx, params)
	return err
}

// PostApiV1InventoryWarehouses converts echo context to params.
func (w *ServerInterfaceWrapper) PostApiV1InventoryWarehouses(ctx echo.Context) error {
	var err error

	ctx.Set(JwtAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostApiV1InventoryWarehouses(ctx)
	return err
}

// DeleteApiV1InventoryWarehousesWarehouseId converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteApiV1InventoryWarehousesWarehouseId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "warehouseId" -------------
	var warehouseId WarehouseId

	err = runtime.BindStyledParameterWithOptions("simple", "warehouseId", ctx.Param("warehouseId"), &warehouseId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter warehouseId: %s", err))
	}

	ctx.Set(JwtAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteApiV1InventoryWarehousesWarehouseId(ctx, warehouseId)
	return err
}

// GetApiV1InventoryWarehousesWarehouseId converts echo context to params.
func (w *ServerInterfaceWrapper) GetApiV1InventoryWarehousesWarehouseId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "warehouseId" -------------
	var warehouseId WarehouseId

	err = runtime.BindStyledParameterWithOptions("simple", "warehouseId", ctx.Param("warehouseId"), &warehouseId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter warehouseId: %s", err))
	}

	ctx.Set(JwtAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetApiV1InventoryWarehousesWarehouseId(ctx, warehouseId)
	return err
}

// PutApiV1InventoryWarehousesWarehouseId converts echo context to params.
func (w *ServerInterfaceWrapper) PutApiV1InventoryWarehousesWarehouseId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "warehouseId" -------------
	var warehouseId WarehouseId

	err = runtime.BindStyledParameterWithOptions("simple", "warehouseId", ctx.Param("warehouseId"), &warehouseId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter warehouseId: %s", err))
	}

	ctx.Set(JwtAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PutApiV1InventoryWarehousesWarehouseId(ctx, warehouseId)
	return err
}

// GetHealth converts echo context to params.
func (w *ServerInterfaceWrapper) GetHealth(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetHealth(ctx)
	return err
}

// GetReady converts echo context to params.
func (w *ServerInterfaceWrapper) GetReady(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetReady(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/api/v1/inventory/categories", wrapper.GetApiV1InventoryCategories)
	router.POST(baseURL+"/api/v1/inventory/categories", wrapper.PostApiV1InventoryCategories)
	router.DELETE(baseURL+"/api/v1/inventory/categories/:categoryId", wrapper.DeleteApiV1InventoryCategoriesCategoryId)
	router.GET(baseURL+"/api/v1/inventory/categories/:categoryId", wrapper.GetApiV1InventoryCategoriesCategoryId)
	router.PUT(baseURL+"/api/v1/inventory/categories/:categoryId", wrapper.PutApiV1InventoryCategoriesCategoryId)
	router.GET(baseURL+"/api/v1/inventory/health", wrapper.GetInventoryHealth)
	router.GET(baseURL+"/api/v1/inventory/movements", wrapper.GetApiV1InventoryMovements)
	router.POST(baseURL+"/api/v1/inventory/movements/adjustment", wrapper.PostApiV1InventoryMovementsAdjustment)
	router.POST(baseURL+"/api/v1/inventory/movements/inbound", wrapper.PostApiV1InventoryMovementsInbound)
	router.POST(baseURL+"/api/v1/inventory/movements/outbound", wrapper.PostApiV1InventoryMovementsOutbound)
	router.POST(baseURL+"/api/v1/inventory/movements/transfer", wrapper.PostApiV1InventoryMovementsTransfer)
	router.GET(baseURL+"/api/v1/inventory/movements/:movementId", wrapper.GetApiV1InventoryMovementsMovementId)
	router.POST(baseURL+"/api/v1/inventory/movements/:movementId/cancel", wrapper.PostApiV1InventoryMovementsMovementIdCancel)
	router.POST(baseURL+"/api/v1/inventory/movements/:movementId/confirm", wrapper.PostApiV1InventoryMovementsMovementIdConfirm)
	router.GET(baseURL+"/api/v1/inventory/products", wrapper.GetApiV1InventoryProducts)
	router.POST(baseURL+"/api/v1/inventory/products", wrapper.PostApiV1InventoryProducts)
	router.DELETE(baseURL+"/api/v1/inventory/products/:productId", wrapper.DeleteApiV1InventoryProductsProductId)
	router.GET(baseURL+"/api/v1/inventory/products/:productId", wrapper.GetApiV1InventoryProductsProductId)
	router.PUT(baseURL+"/api/v1/inventory/products/:productId", wrapper.PutApiV1InventoryProductsProductId)
	router.POST(baseURL+"/api/v1/inventory/products/:productId/restore", wrapper.PostApiV1InventoryProductsProductIdRestore)
	router.GET(baseURL+"/api/v1/inventory/warehouses", wrapper.GetApiV1InventoryWarehouses)
	router.POST(baseURL+"/api/v1/inventory/warehouses", wrapper.PostApiV1InventoryWarehouses)
	router.DELETE(baseURL+"/api/v1/inventory/warehouses/:warehouseId", wrapper.DeleteApiV1InventoryWarehousesWarehouseId)
	router.GET(baseURL+"/api/v1/inventory/warehouses/:warehouseId", wrapper.GetApiV1InventoryWarehousesWarehouseId)
	router.PUT(baseURL+"/api/v1/inventory/warehouses/:warehouseId", wrapper.PutApiV1InventoryWarehousesWarehouseId)
	router.GET(baseURL+"/health", wrapper.GetHealth)
	router.GET(baseURL+"/ready", wrapper.GetReady)

}
